name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - macos-12
          - windows-latest
        exclude: #added
          - os: macos-12 #added
            py-version: 3.9 #added
        py-version: 
          - 3.7 
          - 3.8
          - 3.9
    runs-on: '${{matrix.os}}'
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '${{matrix.pyversion}}'
        
